// src/lib/parkStates.ts
export const PARK_STATE_BY_SLUG: Record<string, string> = {
  "acadia": "Maine",
  "american-samoa": "American Samoa",
  "arches": "Utah",
  "badlands": "South Dakota",
  "big-bend": "Texas",
  "biscayne": "Florida",
  "black-canyon-of-the-gunnison": "Colorado",
  "bryce-canyon": "Utah",
  "canyonlands": "Utah",
  "capitol-reef": "Utah",
  "carlsbad-caverns": "New Mexico",
  "channel-islands": "California",
  "congaree": "South Carolina",
  "crater-lake": "Oregon",
  "cuyahoga-valley": "Ohio",
  "death-valley": "California, Nevada",
  "denali": "Alaska",
  "dry-tortugas": "Florida",
  "everglades": "Florida",
  "gates-of-the-arctic": "Alaska",
  "gateway-arch": "Missouri",
  "glacier": "Montana",
  "glacier-bay": "Alaska",
  "grand-canyon": "Arizona",
  "grand-teton": "Wyoming",
  "great-basin": "Nevada",
  "great-sand-dunes": "Colorado",
  "great-smoky-mountains": "North Carolina, Tennessee",
  "guadalupe-mountains": "Texas",
  "haleakala": "Hawaii",
  "hawaii-volcanoes": "Hawaii",
  "hot-springs": "Arkansas",
  "indiana-dunes": "Indiana",
  "isle-royale": "Michigan",
  "joshua-tree": "California",
  "katmai": "Alaska",
  "kenai-fjords": "Alaska",
  "kings-canyon": "California",
  "kobuk-valley": "Alaska",
  "lake-clark": "Alaska",
  "lassen-volcanic": "California",
  "mammoth-cave": "Kentucky",
  "mesa-verde": "Colorado",
  "mount-rainier": "Washington",
  "new-river-gorge": "West Virginia",
  "north-cascades": "Washington",
  "olympic": "Washington",
  "petrified-forest": "Arizona",
  "pinnacles": "California",
  "redwood": "California",
  "rocky-mountain": "Colorado",
  "saguaro": "Arizona",
  "sequoia": "California",
  "shenandoah": "Virginia",
  "theodore-roosevelt": "North Dakota",
  "virgin-islands": "U.S. Virgin Islands",
  "voyageurs": "Minnesota",
  "white-sands": "New Mexico",
  "wind-cave": "South Dakota",
  "wrangell-st-elias": "Alaska",
  "yellowstone": "Wyoming, Montana, Idaho",
  "yosemite": "California",
  "zion": "Utah",
};
