// src/lib/parkQuotes.ts
export const PARK_QUOTES_BY_SLUG: Record<string, string> = {
  "acadia": "Where mountains greet the Atlantic at dawn.",
  "american-samoa": "Where rainforest and reef breathe as one.",
  "arches": "Stone arches sculpted by wind and patience.",
  "badlands": "A land carved by time, wild and uncompromising.",
  "big-bend": "Vast desert silence beneath endless skies.",
  "biscayne": "Beneath the waves, a hidden wilderness thrives.",
  "black-canyon-of-the-gunnison": "Where darkness plunges into breathtaking depth.",
  "bryce-canyon": "A cathedral of stone carved in light.",
  "canyonlands": "An untamed maze etched by rivers and time.",
  "capitol-reef": "Desert cliffs folded like a sleeping earth.",
  "carlsbad-caverns": "A silent kingdom hidden beneath the desert.",
  "channel-islands": "Wild isles shaped by wind and sea.",
  "congaree": "Ancient forests rising from quiet floodwaters.",
  "crater-lake": "An impossibly blue mirror of volcanic fire.",
  "cuyahoga-valley": "Nature reclaiming the rhythm of the land.",
  "death-valley": "Extreme beauty forged in relentless heat.",
  "denali": "Where the great mountain rules the horizon.",
  "dry-tortugas": "History and sea meeting at the edge of the Gulf.",
  "everglades": "A slow-moving river of grass and life.",
  "gates-of-the-arctic": "Pure wilderness, untouched and uncompromising.",
  "gateway-arch": "A monument to movement, expansion, and possibility.",
  "glacier": "Ancient ice and alpine silence.",
  "glacier-bay": "Where ice meets ocean in quiet grandeur.",
  "grand-canyon": "Vast, timeless, and humbling beyond words.",
  "grand-teton": "Sharp peaks rising from tranquil valleys.",
  "great-basin": "Ancient bristlecones beneath star-filled skies.",
  "great-sand-dunes": "Mountains of sand shaped by wind and wonder.",
  "great-smoky-mountains": "Mist, mountains, and endless forest breath.",
  "guadalupe-mountains": "Desert peaks standing firm against time.",

  // IMPORTANT: use ascii slug for your filenames/urls
  "haleakala": "A sun-born summit above the clouds.",
  "hawaii-volcanoes": "Where the earth creates itself anew.",

  "hot-springs": "Where healing waters rise from the earth.",
  "indiana-dunes": "Shifting sands along a freshwater sea.",
  "isle-royale": "Isolation shaped by water and wilderness.",
  "joshua-tree": "Where desert and dream converge.",
  "katmai": "Wild rivers, brown bears, and raw power.",
  "kenai-fjords": "Ice-carved coastlines alive with motion.",
  "kings-canyon": "Deep valleys guarded by towering stone.",
  "kobuk-valley": "Endless dunes beneath Arctic skies.",
  "lake-clark": "Untamed beauty where land and water collide.",
  "lassen-volcanic": "A restless landscape shaped by fire.",
  "mammoth-cave": "The world's longest story written underground.",
  "mesa-verde": "Stone homes whispering stories of the past.",
  "mount-rainier": "A solitary giant crowned in snow.",
  "new-river-gorge": "Ancient river, enduring stone, endless adventure.",
  "north-cascades": "Rugged peaks lost in clouds and quiet.",
  "olympic": "Many worlds woven into one wilderness.",
  "petrified-forest": "Ancient trees frozen in time and color.",
  "pinnacles": "Volcanic spires alive with motion.",
  "redwood": "Cathedrals of forest rising toward the sky.",
  "rocky-mountain": "High passes where earth meets sky.",
  "saguaro": "Sentinels of the desert standing tall.",
  "sequoia": "Home to giants older than memory.",
  "shenandoah": "Rolling mountains wrapped in quiet beauty.",
  "theodore-roosevelt": "Wild lands that shaped a conservation legacy.",
  "virgin-islands": "Turquoise waters framing tropical serenity.",
  "voyageurs": "A maze of water, sky, and silence.",
  "white-sands": "Dunes of light under an open sky.",
  "wind-cave": "Hidden patterns beneath the prairie.",
  "wrangell-st-elias": "Immensity untouched by human scale.",
  "yellowstone": "Where the earth breathes fire and steam.",
  "yosemite": "Where granite giants sleep beneath endless skies.",
  "zion": "Towering cliffs and quiet reverence in every canyon.",
};
